name: Musinsa Daily Crawler

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      # ⭐️ 이 부분(token 추가)으로 바꿔주세요!
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas

      - name: Run crawler script
        run: python crawler.py

      - name: Commit and push changes if data updated
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add musinsa_new_ranking_top100.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Auto-update Musinsa ranking CSV data" && git push)